* [pandas-datareader](https://pandas-datareader.readthedocs.io/en/latest/remote_data.html)

* [DataFrame](https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python)

In [79]:
import pandas as pd
import pandas_datareader.data as web
import datetime

#DATA_SOURCE = "morningstar"
DATA_SOURCE = "google"
#DATA_SOURCE = "yahoo"

#start = datetime.datetime(1993,1,1)
#end = datetime.date.today()

#spy = web.DataReader("SPY", DATA_SOURCE, start, end)
raw_spy = pd.read_csv("SPY.csv")
raw_spy = raw_spy.set_index("Date")

raw_spy
#spy.to_csv("SPY.csv")

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1993-01-29,43.968700,43.968700,43.750000,43.937500,27.466887,1003200
1993-02-01,43.968700,44.250000,43.968700,44.250000,27.662252,480500
1993-02-02,44.218700,44.375000,44.125000,44.343700,27.720823,201300
1993-02-03,44.406200,44.843700,44.375000,44.812500,28.013882,529400
1993-02-04,44.968700,45.093700,44.468700,45.000000,28.131090,531500
1993-02-05,44.968700,45.062500,44.718700,44.968700,28.111523,492100
1993-02-08,44.968700,45.125000,44.906200,44.968700,28.111523,596100
1993-02-09,44.812500,44.812500,44.562500,44.656200,27.916172,122100
1993-02-10,44.656200,44.750000,44.531200,44.718700,27.955238,379600
1993-02-11,44.781200,45.125000,44.781200,44.937500,28.092035,19500
1993-02-12,44.875000,44.875000,44.593700,44.593700,27.877092,42500
1993-02-16,44.468700,44.468700,43.406200,43.468700,27.173828,374800
1993-02-17,43.468700,43.531200,43.281200,43.437500,27.154329,210900
1993-02-18,43.937500,43.937500,42.812500,43.406200,27.134754,378100
1993-02-19,43.406200,43.562500,43.343700,43.562500,27.232456,34900
1993-02-22,43.687500,43.781200,43.562500,43.718700,27.330091,513600
1993-02-23,43.843700,43.875000,43.468700,43.687500,27.310616,373700
1993-02-24,43.718700,44.250000,43.718700,44.250000,27.662252,26300
1993-02-25,44.218700,44.375000,44.125000,44.343700,27.720823,44500
1993-02-26,44.437500,44.437500,44.187500,44.406200,27.759888,66200
1993-03-01,44.562500,44.562500,44.218700,44.281200,27.681738,66500
1993-03-02,44.312500,44.937500,44.250000,44.937500,28.092035,182400
1993-03-03,45.000000,45.156200,44.937500,45.125000,28.209244,280100
1993-03-04,45.187500,45.187500,44.875000,44.875000,28.052954,89500
1993-03-05,44.937500,45.125000,44.718700,44.750000,27.974813,40000
1993-03-08,44.843700,45.750000,44.843700,45.750000,28.599939,50800
1993-03-09,45.656200,45.687500,45.500000,45.593700,28.502234,169300
1993-03-10,45.593700,45.687500,45.406200,45.687500,28.560865,194400
1993-03-11,45.718700,45.843700,45.500000,45.562500,28.482754,70900
1993-03-12,45.187500,45.218700,44.812500,45.093700,28.189665,643600
...,...,...,...,...,...,...
2018-01-05,272.510010,273.559998,271.950012,273.420013,273.420013,83524000
2018-01-08,273.309998,274.100006,272.980011,273.920013,273.920013,57319200
2018-01-09,274.399994,275.250000,274.079987,274.540009,274.540009,57254000
2018-01-10,273.679993,274.420013,272.920013,274.119995,274.119995,69574300
2018-01-11,274.750000,276.119995,274.559998,276.119995,276.119995,62361500
2018-01-12,276.420013,278.109985,276.079987,277.920013,277.920013,90816100
2018-01-16,279.350006,280.089996,276.179993,276.970001,276.970001,106555100
2018-01-17,278.029999,280.049988,276.970001,279.609985,279.609985,113258800
2018-01-18,279.480011,279.959991,278.579987,279.140015,279.140015,100728000
2018-01-19,279.799988,280.410004,279.140015,280.410004,280.410004,140920100
2018-01-22,280.170013,282.690002,280.109985,282.690002,282.690002,91322400
2018-01-23,282.739990,283.619995,282.369995,283.290009,283.290009,97084700
2018-01-24,284.019989,284.700012,281.839996,283.179993,283.179993,134816100
2018-01-25,284.160004,284.269989,282.399994,283.299988,283.299988,84587300
2018-01-26,284.250000,286.579987,283.959991,286.579987,286.579987,107743100
2018-01-29,285.929993,286.429993,284.500000,284.679993,284.679993,90118300
2018-01-30,282.600006,284.739990,281.220001,281.760010,281.760010,131796400
2018-01-31,282.730011,283.299988,280.679993,281.899994,281.899994,108364800
2018-02-01,281.070007,283.059998,280.679993,281.579987,281.579987,90102500
2018-02-02,280.079987,280.230011,275.410004,275.450012,275.450012,173174800
2018-02-05,273.450012,275.850006,263.309998,263.929993,263.929993,294681800
2018-02-06,259.940002,269.700012,258.700012,269.130005,269.130005,355026800
2018-02-07,268.500000,272.359985,267.579987,267.670013,267.670013,167376100
2018-02-08,268.010010,268.170013,257.589996,257.630005,257.630005,246449500
2018-02-09,260.799988,263.609985,252.919998,261.500000,261.500000,283565300
2018-02-12,263.829987,267.010010,261.660004,265.339996,265.339996,143736000
2018-02-13,263.970001,266.619995,263.309998,266.000000,266.000000,81223600
2018-02-14,264.309998,270.000000,264.299988,269.589996,269.589996,120735700
2018-02-15,271.570007,273.040009,268.769989,273.029999,273.029999,111200300
2018-02-16,272.320007,275.320007,272.269989,273.109985,273.109985,152272300

In [77]:
def ToMonthStr(month):
    return str(month) if month >= 10 else "0%s" % str(month)

def GenMonFromdaily(dailyDf, year, month):
    monthStr = ToMonthStr(month)
    start = '%s-%s-01' % (year, monthStr)
    end = '%s-%s-31' % (year, monthStr)
    tmp = dailyDf.loc[start:end]
    #return [tmp.iloc[0]['Open'], max(tmp.loc[:,'High']), min(tmp.loc[:,'Low']), tmp.iloc[-1]['Close'], sum(tmp.loc[:,'Volume'])]
    return [tmp.iloc[0]['Open'], tmp.iloc[0]['High'], tmp.iloc[0]['Low'], tmp.iloc[0]['Close'], tmp.iloc[0]['Volume']]
    #return [tmp.iloc[0]['Open'], tmp.iloc[0]['High'], tmp.iloc[0]['Low'], tmp.iloc[0]['Close'], 5]

In [78]:
monthly_spy = pd.DataFrame(columns=['Open','High','Low','Close','Volume'])
for year in range(1993,2018):
    for month in range(1,13):
        monthly_spy.loc["%s-%s" % (year, ToMonthStr(month))] = GenMonFromdaily(raw_spy, year, month)
        
monthly_spy.loc['2018-01'] = GenMonFromdaily(raw_spy, 2018, 1)
monthly_spy.loc['2018-02'] = GenMonFromdaily(raw_spy, 2018, 2)
monthly_spy

               Open        High         Low       Close       Volume
1993-01   43.968700   43.968700   43.750000   43.937500    1003200.0
1993-02   43.968700   44.250000   43.968700   44.250000     480500.0
1993-03   44.562500   44.562500   44.218700   44.281200      66500.0
1993-04   45.250000   45.250000   44.937500   45.031200     129500.0
1993-05   44.093700   44.312500   43.906200   44.312500      80500.0
1993-06   45.375000   45.812500   45.312500   45.656200      28300.0
1993-07   45.125000   45.125000   44.875000   44.937500     605700.0
1993-08   44.906200   45.125000   44.906200   44.968700      41300.0
1993-09   46.406200   46.593700   46.406200   46.500000     136500.0
1993-10   45.875000   46.218700   45.812500   46.156200      22700.0
1993-11   46.781200   47.000000   46.781200   46.968700      36400.0
1993-12   46.593700   46.625000   46.406200   46.406200     379200.0
1994-01   46.593700   46.656200   46.406200   46.468700     960900.0
1994-02   48.156200   48.156200   47.906200   47.968700     303600.0
1994-03   46.812500   46.906200   46.375000   46.625000     423600.0
1994-04   43.343700   44.031200   43.343700   43.906200    2627300.0
1994-05   45.093700   45.718700   44.937500   45.375000     275000.0
1994-06   45.703098   46.015598   45.562500   46.015598     200500.0
1994-07   44.687500   44.687500   44.375000   44.562500     406900.0
1994-08   45.937500   46.156200   45.890598   46.125000     486300.0
1994-09   47.500000   47.531200   47.328098   47.500000     294600.0
1994-10   46.203098   46.250000   45.984299   46.062500      72600.0
1994-11   47.281200   47.281200   46.937500   46.953098     435200.0
1994-12   45.640598   45.640598   45.046799   45.140598     439000.0
1995-01   45.703098   45.843700   45.687500   45.781200     324300.0
1995-02   47.156200   47.328098   47.000000   47.078098     380200.0
1995-03   48.968700   49.031200   48.656200   48.703098     242600.0
1995-04   50.093700   50.234299   50.062500   50.234299     193300.0
1995-05   51.546799   51.656200   51.453098   51.453098     518700.0
1995-06   53.406200   53.906200   53.250000   53.500000     810100.0
...             ...         ...         ...         ...          ...
2015-09  193.119995  194.770004  190.729996  191.770004  256000400.0
2015-10  192.080002  192.490005  189.820007  192.130005  131079000.0
2015-11  208.320007  210.619995  208.169998  210.389999   86270800.0
2015-12  209.440002  210.820007  209.110001  210.679993   97858400.0
2016-01  200.490005  201.029999  198.589996  201.020004  222353500.0
2016-02  192.529999  194.580002  191.839996  193.649994  136061600.0
2016-03  195.009995  198.210007  194.449997  198.110001  141799700.0
2016-04  204.350006  207.139999  203.979996  206.919998  114423500.0
2016-05  206.919998  208.179993  206.410004  207.970001   62188000.0
2016-06  209.119995  210.479996  208.889999  210.270004   69936200.0
2016-07  209.479996  210.490005  209.289993  209.919998  106055300.0
2016-08  217.190002  217.649994  216.410004  216.940002   73311400.0
2016-09  217.369995  217.729996  216.029999  217.389999   97844200.0
2016-10  215.820007  216.039993  215.039993  215.779999   83512100.0
2016-11  212.929993  212.990005  209.600006  211.009995  122781800.0
2016-12  220.729996  220.729996  219.149994  219.570007   79040500.0
2017-01  225.039993  225.830002  223.880005  225.240005   91366500.0
2017-02  227.529999  228.589996  226.940002  227.619995   79117700.0
2017-03  238.389999  240.320007  238.369995  239.779999  149158200.0
2017-04  235.800003  236.029999  233.910004  235.330002   85546500.0
2017-05  238.679993  239.169998  238.199997  238.679993   66882500.0
2017-06  241.970001  243.380005  241.639999  243.360001   68962000.0
2017-07  242.880005  243.380005  242.210007  242.210007   39153800.0
2017-08  247.460007  247.500000  246.720001  247.320007   55050400.0
2017-09  247.919998  248.330002  247.669998  247.839996   62007000.0
2017-10  251.490005  252.320007  251.289993  252.320007   59023000.0
2017-11  258.040009  258.429993  257.070007  257.489990   54202700.0
2017-12  264.760010  265.309998  260.760010  264.459991  164390900.0
2018-01  267.839996  268.809998  267.399994  268.769989   86655700.0
2018-02  281.070007  283.059998  280.679993  281.579987   90102500.0

[302 rows x 5 columns]